name: Send Email

on:
  schedule:
    - cron: '0 9 * * *' # 每天早上 9 点发送邮件

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      
    - name: Send email
      run: |
        php send_email.php
