name: Send Email

on: [push]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      
    - name: Send email
      run: |
        php send_email.php ${{ secrets.TO_ADDR }} ${{ secrets.FROM_ADDR }} ${{ secrets.PASSWORD }} ${{ secrets.SMTP_SERVER }} ${{ secrets.SMTP_PORT }}
      env:
        TO_ADDR: ${{ secrets.TO_ADDR }}
        FROM_ADDR: ${{ secrets.FROM_ADDR }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
